### PR TITLE
Replaced a for loop that initialized a dict

### PR DESCRIPTION
**Pull request by surajssd**
Replaced the for loop that initialized the dict with keys similar to other dict and values as None, using the `dict` datatype function called `fromkeys`

### CODE REVIEW

**Comment by dustymabe** [comment]
LGTM

**Comment by dustymabe** [comment]
#dotests

**Comment by kadel** [comment]
LGTM

**Comment by cdrage** [comment]
Hey @surajssd sorry for the delay!

Mind rebasing this against master? Just going to test one more thing. I know it's a bit redundant, just saw that it broke against current tests but I think it's cause of the updates to adb-tests and the updated provider params.

**Comment by surajssd** [comment]
@cdrage sure will rebase that!

**Comment by cdrage** [comment]
Tests pass :+1:

**Comment by cdrage** [comment]
LGTM

**Pull request merged**
