### PR TITLE
Fix CentOS CI Errors

### PR DESCRIPTION
**Pull request by cdrage**
Don't know *exactly* why it's failing, but let's try this. Could be
related to "foobar" actually going to an internal server.

### CODE REVIEW

**Comment by cdrage** [comment]
#dotests

**Comment by cdrage** [comment]
yay, looks like it fixed the tests, going to fix this "upstream" too in kubeshift.

**Comment by dustymabe** [comment]
should we try to understand the situation here a bit more? would be nice to know the root cause.

**Comment by cdrage** [comment]
No idea :( i can try pinging "foobar" from within the infrastructure and see what's up

**Pull request merged**
