### PR TITLE
Add genanswers toplevel action.

### PR DESCRIPTION
**Pull request by dustymabe**
See #467

### CODE REVIEW

**Comment by rtnpro** [comment]
LGTM :+1: 

What about using ``get-anwers`` in place of ``genanswers``?

**Comment by dustymabe** [comment]
> What about using get-anwers in place of genanswers?

I like "generate answers" because it implies that there is some "work" that is being done by the Atomic App code; it has to get all the artifacts from nested nulecules so that it can generate the answers.conf file. The answers.conf file isn't something we simply copy out, but have to actually generate.
 
That is the way it is now.. With your proposed work on answers for nested nulecules would this change?

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by dustymabe** [comment]
Just performed rebase.. merging now

**Pull request merged**
