### PR TITLE
Added code for cli auto-complete for atomicapp

### PR DESCRIPTION
**Pull request by shiminsh**

### CODE REVIEW

**Comment by rtnpro** [comment]
@shiminsh Thanks for the pull request. The initial work looks good. However, we can do some improvements:
- let's keep the shell script out of the python package, let's follow what ``atomic`` CLI is doing, https://github.com/projectatomic/atomic/blob/master/bash/atomic
- we should 4 spaces for a ``TAB``
- we need to support the commands: ``run``, ``stop``, etc and their options as well

Let us know if you need some help.

**Comment by shiminsh** [comment]
Thanks, I'm looking into it for improvements. I'll ask for help if needed.

**Comment by shiminsh** [comment]
@rtnpro Please explain a little bit third point which other options as I have mention run and stop command in my script.

**Comment by surajssd** [comment]
@shiminsh have you looked into https://github.com/projectatomic/atomicapp/issues/636#issuecomment-206433211 ?

**Comment by cdrage** [comment]
Hi @shiminsh thanks for the contribution. We're going to close this for now until we find an alternative way to generate the auto-completion scripts.

**Comment by shiminsh** [comment]
Okay.

**Pull request closed without merging**
