### PR TITLE
Added yum update to Dockerfile

### PR DESCRIPTION
**Pull request by surajssd**
Added `yum update` in Dockerfile of project root directory.

Fixes issue #591

### CODE REVIEW

**Comment by goern** [comment]
shouldnt that be the last command before `yum clean all`?

**Comment by surajssd** [comment]
@goern why is that so?

**Comment by goern** [comment]
maybe you are right and it doesnt matter, and is just a matter of habit...

**Comment by cdrage** [comment]
As long as there is a `yum clean all` at the very end i don't see an issue..

**Comment by surajssd** [comment]
I am still not very clear about what is correct way to go?

**Comment by cdrage** [comment]
yum update at the top or the bottom shouldn't matter since the image size will still remain the same :+1: this LGTM

**Comment by surajssd** [comment]
okay now its clear to me :)

**Comment by dustymabe** [comment]
I think some of the consensus recently around the yum update vs not is that if you are basing your image on a source image (centos/rhel/debian/etc) that gets properly updated regularly then you shouldn't need to do an update yourself. 

Either way, it is fine if we want to go that approach

**Comment by dustymabe** [comment]
@kbsingh - do you have an guidance on this issue (and more specifically on the previous comment). Do you have any strong opinions on whether we should be using yum update -y in our Dockerfiles vs trusting the container we are using as a base?

**Comment by bexelbie** [comment]
@surajssd Consider the comment about updates here:

https://github.com/projectatomic/container-best-practices/blob/9ac2688de11d5576090b6d97d04ba2454e423bf5/creating/creating_index.adoc

I believe that we should just figure out what the stated update pattern is for the CentOS base and follow through with that.  I believe we are going to find it something we can rely on.

**Comment by surajssd** [comment]
@bexelbie I could not find any written guidelines, but looking at the [Fedora-Dockerfiles](https://github.com/fedora-cloud/Fedora-Dockerfiles) I feel its widely accepted convention to update.

**Comment by bexelbie** [comment]
@surajssd "Updates - Not all community images are necessarily rebuilt on a regular basis or when security vulnerabilities are addressed. You should therefore consider using base images from "official repositories" on Docker Hub, and confirm their update policy in advance."

**Comment by surajssd** [comment]
@bexelbie so that means its a safe thing to update right?

**Comment by bexelbie** [comment]
@surajssd as I understand it, reproducibility and in some ways thinking about what works comes down to not running `yum update`.  If Fedora has an acceptable update policy, I think we should not add `yum update`.  If they are not updating their container we should both do a `yum update` and push on them :)

**Comment by surajssd** [comment]
Who is the right guy from CentOS community to comment on this? Because I was not able to find anything documented in this regard.

**Comment by jperrin** [comment]
The base centos containers are rebuilt monthly, and that cadence may increase. Putting a ```yum -y update``` into the Dockerfile will in many cases be a no-op. If the containers are being properly refreshed and rebuilt I don't see a need to include the update.

**Comment by cdrage** [comment]
Thanks for the inisight @jperrin ! With your comment I shall close this issue. We'll rely on CentOS Docker images being up-to-date instead of `yum update`

**Pull request closed without merging**
