### PR TITLE
Use filter to search in kubeconfig.py

### PR DESCRIPTION
**Pull request by surajssd**
Using filter function to search in iterable on a single key. Optimized code in kubeconfig.py

### CODE REVIEW

**Comment by cdrage** [comment]
#dotests

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by kadel** [comment]
LGTM

**Comment by cdrage** [comment]
OpenShift tests pass locally on my machine + centos CI (which is what kubeconfig is only affecting right now).

This looks good to me! Merging.

**Pull request merged**
