### PR TITLE
Add in cli options for some provider* answers.

### PR DESCRIPTION
**Pull request by dustymabe**
Add in cli options for some provider* answers.                                                 
                                                                               
Probably the most useful of these is --providertlsverify since it will
enable people to easily disable tls verification if necessary.

### CODE REVIEW

**Comment by dustymabe** [comment]
please review #505 first

**Comment by kadel** [comment]
LGTM

**Comment by dustymabe** [comment]
ok rebased on master..

**Comment by cdrage** [comment]
Error on atomicapp run using `docker` provider:
```
##########
run: TESTING HELLOAPACHE EXAMPLE
##########

Sending build context to Docker daemon  12.8 kB
Step 0 : FROM atomicapp:build
 ---> dbb7ed5c501a
Step 1 : MAINTAINER Red Hat, Inc. <container-tools@redhat.com>
 ---> Running in 70a3180c10c8
 ---> 376361e3a31d
Removing intermediate container 70a3180c10c8
Step 2 : LABEL io.projectatomic.nulecule.providers "kubernetes,docker" io.projectatomic.nulecule.specversion "0.0.2"
 ---> Running in b4d20fb1374c
 ---> 244d2555c4be
Removing intermediate container b4d20fb1374c
Step 3 : ADD /Nulecule /Dockerfile README.md /application-entity/
 ---> 71ed4d8d503a
Removing intermediate container 1eac76ab0808
Step 4 : ADD /artifacts /application-entity/artifacts
 ---> a696beee383a
Removing intermediate container e84bbcc26cd2
Successfully built a696beee383a
docker run -it --rm  --privileged -v /home/wikus/dropbox/dev/adb-tests/cdrage-atomicapp-ci:/atomicapp -v /run:/run -v /:/host --net=host --name helloapache -e NAME=helloapache -e IMAGE=projectatomic/helloapache projectatomic/helloapache -v  run  projectatomic/helloapache --provider=docker -a answers.conf --destination=build
docker run -it --rm  --privileged -v /home/wikus/dropbox/dev/adb-tests/cdrage-atomicapp-ci:/atomicapp -v /run:/run -v /:/host --net=host --name helloapache -e NAME=helloapache -e IMAGE=projectatomic/helloapache projectatomic/helloapache -v  run  projectatomic/helloapache --provider=docker -a answers.conf --destination=build
2016-01-14 17:12:42,327 - __main__ - INFO - Action/Mode Selected is: run
2016-01-14 17:12:42,328 - __main__ - DEBUG - Final parsed cmdline: run -v projectatomic/helloapache --provider=docker -a answers.conf --destination=build
2016-01-14 17:12:42,328 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: build
2016-01-14 17:12:42,328 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: projectatomic/helloapache
2016-01-14 17:12:42,328 - atomicapp.utils - DEBUG - Loading answers from file: answers.conf
2016-01-14 17:12:42,329 - atomicapp.nulecule.main - DEBUG - Request to unpack to projectatomic/helloapache to build
2016-01-14 17:12:42,329 - atomicapp.nulecule.base - INFO - Unpacking image: projectatomic/helloapache to build
2016-01-14 17:12:44,356 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: projectatomic/helloapache
2016-01-14 17:12:44,356 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: projectatomic/helloapache to build
2016-01-14 17:12:44,356 - atomicapp.nulecule.container - DEBUG - Creating docker container: /usr/bin/docker create --entrypoint /bin/true projectatomic/helloapache
2016-01-14 17:12:44,482 - atomicapp.nulecule.container - DEBUG - Copying data from Docker container: /usr/bin/docker cp 9f437e41c3204c9c02d131756bbe4fe9cb012f250385c39d7ad67e2a62daa2f8:/application-entity /tmp/nulecule-06d76934-bae2-11e5-a7b3-3402868080db
2016-01-14 17:12:44,543 - atomicapp.nulecule.container - DEBUG - Copying nulecule data from /tmp/nulecule-06d76934-bae2-11e5-a7b3-3402868080db to build
2016-01-14 17:12:44,546 - atomicapp.nulecule.container - DEBUG - Removing tmp dir: /tmp/nulecule-06d76934-bae2-11e5-a7b3-3402868080db
2016-01-14 17:12:44,547 - atomicapp.utils - DEBUG - Recursively removing directory: /tmp/nulecule-06d76934-bae2-11e5-a7b3-3402868080db
2016-01-14 17:12:44,548 - atomicapp.nulecule.container - DEBUG - Removing Docker container: /usr/bin/docker rm -f 9f437e41c3204c9c02d131756bbe4fe9cb012f250385c39d7ad67e2a62daa2f8
9f437e41c3204c9c02d131756bbe4fe9cb012f250385c39d7ad67e2a62daa2f8
2016-01-14 17:12:44,642 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2016-01-14 17:12:44,643 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2016-01-14 17:12:44,645 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2016-01-14 17:12:44,645 - __main__ - ERROR - 'NoneType' object has no attribute 'lstrip'
Traceback (most recent call last):
  File "/opt/atomicapp/atomicapp/cli/main.py", line 100, in cli_run
    nm.run(**argdict)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 246, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 147, in run
    provider_key, provider = self.get_provider(provider_key, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/lib.py", line 99, in get_provider
    self.get_context(), self.basepath, dry)
  File "/opt/atomicapp/atomicapp/plugin.py", line 60, in __init__
    self.getConfigFile()
  File "/opt/atomicapp/atomicapp/plugin.py", line 76, in getConfigFile
    self.config_file = os.path.join(Utils.getRoot(), self.config_file.lstrip("/"))
AttributeError: 'NoneType' object has no attribute 'lstrip'
```

**Comment by dustymabe** [comment]
The issue was that the provider* values were getting set in cli_answers even though the user didn't provide anything for them.

**Comment by cdrage** [comment]
Code LGTM :+1: 

Docker, Kubernetes and OpenShift tests pass.

However, we should add a test to this so that any CLI parameters we pass with the new options are actually passed into `answers`

**Comment by dustymabe** [comment]
Opened #508 to document need of unit tests for this PR. Merging..

**Pull request merged**
