### PR TITLE
added cli completion support.

### PR DESCRIPTION
**Pull request by abhi1004**
This pr is as per the issue number #636, please review it and let me know your thought and suggestions.

### CODE REVIEW

**Comment by rtnpro** [comment]
Hey @abhi1004, thanks for the patch. Could you and @shiminsh (from #665 ) collaborate on this?

**Comment by abhi1004** [comment]
@rtnpro Sure I will if  @shiminsh agree.

**Comment by shiminsh** [comment]
Yeah, sure @abhi1004

>

**Comment by cdrage** [comment]
I'm going to close this for the time being until we can find an automated way of adding bash auto-completion. Or at least a script that we can use to generate it.

**Pull request closed without merging**
