### PR TITLE
Fix and add constants in the /nulecule dir

### PR DESCRIPTION
**Pull request by cdrage**
This PR fixes the key names (mainly) in the /nulecule dir. It also adds a few more constants which were not yet included to `constants.py`.

### CODE REVIEW

**Comment by charliedrage** [comment]
ping @rtnpro since this relates to his nulecule refactor :)

**Comment by vpavlin** [comment]
LGTM

**Comment by dustymabe** [comment]
LGTM.. @rtnpro ?

**Comment by rtnpro** [comment]
@cdrage :+1: for the fix. I will merge it.

**Pull request merged**
