### PR TITLE
Added cert param in `make_rest_request` to pass client side certs

### PR DESCRIPTION
**Pull request by surajssd**
Added cert param so that now we can pass client side certs while making request to API server, this can be passed as path to file that contains cert and key or it can be a tuple which has path ti cert and key.

This is part of the effort to add support to authenticate to server via cert in addition to access_token.

### CODE REVIEW

**Comment by surajssd** [comment]
This will fix #693 and add to effort going on with #533

**Comment by dustymabe** [comment]
Hey @surajssd this looks great but let's create a PR that solves #533 and includes this commit. You can open a WIP (work in progress) PR if you'd like show progress and gather feedback. 

Also, you don't need an issue in order to create a PR. Just open the PR  :-P

**Comment by surajssd** [comment]
@dustymabe I and @kadel had a discussion and we decided to work on this together, so we divided the tasks into sub-tasks which can be done in separate PRs. I feel that will introduce less bugs, compared to adding a large chunk of code once. Please suggest.

**Comment by cdrage** [comment]
@surajssd Ideally it would be best if one of you just submit the major PR and if you need to change parts of the code you can send a .patch to @kadel for him to edit the code :) This would prevent any major breakage as we'd have to implement and merge in two separate PR's ideally at the same exact time.

**Comment by dustymabe** [comment]
while I have not done this before I think it is possible to do:

you can allow push access to your fork from Tomas and then you can both push changes to the PR that you submit (by updating commits on the branch in your forked repo). If both of you have push access to your repo then you should be able to do that without any issue.

**Comment by rtnpro** [comment]
On Apr 14, 2016 12:00 AM, "Dusty Mabe" <notifications@github.com> wrote:
>
> while I have not done this before I think it is possible to do:
>
> you can allow push access to your fork from Tomas and then you can both
push changes to the PR that you submit (by updating commits on the branch
in your forked repo). If both of you have push access to your repo then you
should be able to do that without any issue.

:+1 This should just work fine.

**Comment by surajssd** [comment]
Closing this PR in response to the PR that @kadel is sending!

**Pull request closed without merging**
