### PR TITLE
add new method find_binary to find executable

### PR DESCRIPTION
**Pull request by sub-mod**
I had to add a new method to find /host/bin/oc file on openshift provider
the existing method did failed if the file is a symbolic link

### CODE REVIEW

**Comment by sub-mod** [comment]
needed for https://github.com/cockpit-project/cockpit/pull/2921

**Comment by charliedrage** [comment]
No need to copy-pasta code. Just use `from distutils.spawn import find_executable`

**Comment by sub-mod** [comment]
@charliedrage 
I have added 
```
 if os.path.isfile(f) or os.path.islink(f)
```
to check /host/bin/oc is a link

**Comment by sub-mod** [comment]
@goern @vpavlin  kindly review

**Comment by charliedrage** [comment]
Ah. That'd do it.

LGTM :+1:

**Pull request merged**
