### PR TITLE
Fixes for answers file processing.

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by dustymabe** [comment]
Part of this PR fixes https://github.com/projectatomic/atomicapp/issues/384

**Comment by charliedrage** [comment]
Still getting an error when stopping.

Would this not work if you haven't provided the answers.conf in the same directory (I'm calling it via image rather than `dir`)

```
dropbox/dev/atomicapp  dusty ✔                                                                                          40m  ⍉
▶ sudo atomicapp -v stop --provider=docker jasonbrooks/kubernetes-atomicapp
2015-11-09 16:22:40,111 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/providers
2015-11-09 16:22:40,118 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-a57e390391a4
2015-11-09 16:22:40,118 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: jasonbrooks/kubernetes-atomicapp
2015-11-09 16:22:40,118 - atomicapp.cli.main - ERROR - Provided answers file does not exist: /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-a57e390391a4/answers.conf.gen
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/cli/main.py", line 88, in cli_stop
    nm.stop(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/nulecule/main.py", line 206, in stop
    os.path.join(self.app_path, ANSWERS_RUNTIME_FILE))
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.2.1-py2.7.egg/atomicapp/utils.py", line 291, in loadAnswers
    "Provided answers file does not exist: %s" % answers_file)
AtomicAppUtilsException: Provided answers file does not exist: /var/lib/atomicapp/jasonbrooks-kubernetes-atomicapp-a57e390391a4/answers.conf.gen
```

**Comment by dustymabe** [comment]
cdrage, right. It really does't make sense (tell me if I'm wrong) to not pass a directory to "stop". The directory that started the app contains information about the app that it needs in order to properly stop it (i.e. which provider it was started with)

**Comment by charliedrage** [comment]
LGTM :+1: From my testing everything works as intended!

**Pull request merged**
