### PR TITLE
Remove instances of install verb to fetch

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by dustymabe** [comment]
Should we also try to go through the code and update any references in the comments to "install" ?

**Comment by cdrage** [comment]
@dustymabe yup, that's what I did!

**Comment by dustymabe** [comment]
@cdrage, what PR are you referring to?

Also here are some more findings:

```
$ grep -Ri install ./atomicapp/
./atomicapp/cli/main.py:                "This will install and run an Atomic App, "
./atomicapp/cli/main.py:                Destination directory for install. This defaults to a
./atomicapp/cli/main.py:                Path to the directory where the Atomic App is installed
./atomicapp/providers/kubernetes.py:        Actions are either: run, stop or uninstall as per the Requirements class
./atomicapp/nulecule/base.py:            A Nulecule instance or None in case of some dry run (installing
./atomicapp/nulecule/base.py:            raise NuleculeException("Installed Nulecule components are required to initiate dry-run. "
./atomicapp/nulecule/lib.py:    def uninstall(self):
./atomicapp/nulecule/main.py:    Interface to install, run, stop a Nulecule application.
./atomicapp/nulecule/main.py:        Installs (unpacks) a Nulecule application from a Nulecule image
./atomicapp/nulecule/main.py:            nodeps (bool): Install the nulecule application without installing
./atomicapp/nulecule/main.py:            update (bool): Pull requisite Nulecule image and install or
./atomicapp/nulecule/main.py:                           update already installed Nulecule application
```

**Comment by cdrage** [comment]
@dustymabe 
updated

I'm refering to #535

**Comment by dustymabe** [comment]
LGTM. Assuming tests pass go ahead and merge.

**Comment by cdrage** [comment]
They did :+1: merging.

**Pull request merged**
