### PR TITLE
reverts break in versioning

### PR DESCRIPTION
**Pull request by charliedrage**
fixes break on versioning in commit #233 
fixes issue #244

### CODE REVIEW

**Comment by dustymabe** [comment]
Would you also want to delete the `VERSION` and the other file and remove them from being included in the Dockerfile? If we decided to do something different for this in the future then that stuff might get left around and forgotten.

**Comment by charliedrage** [comment]
@dustymabe I've pushed a separate commit to the breakin one to remove the dynamic versioning from the Dockerfiles.

**Comment by dustymabe** [comment]
@charliedrage maybe squash into a single commit? Otherwise LGTM

**Comment by charliedrage** [comment]
@dustymabe thought it'd be nice to see what exactly broke :) but gone ahead and squashed!

**Comment by dustymabe** [comment]
LGTM @goern ^^

**Pull request merged**
