### PR TITLE
reimplement --version, improve #481

### PR DESCRIPTION
**Pull request by containscafeine**

### CODE REVIEW

**Comment by cdrage** [comment]
Yay!

```
dropbox/dev/atomicapp  601-containscafeine-version_show ✔                                                                                                                                                                                               48m  ⍉
▶ atomicapp --help
usage: atomicapp [-V] {run,fetch,stop,genanswers} ...

This will fetch and run an Atomic App, a containerized application conforming to the Nulecule Specification

positional arguments:
  {run,fetch,stop,genanswers}

optional arguments:
  -V, --version         show the version and exit.

optional arguments:
  -v, --verbose         Verbose output mode.
  -q, --quiet           Quiet output mode.
  --mode {fetch,run,stop,genanswers}
                        The mode Atomic App is run in. This option has the
                        effect of switching the 'verb' that was passed by the
                        user as the first positional argument. This is useful
                        in cases where a user is not using the Atomic App cli
                        directly, but through another interface such as the
                        Atomic CLI. EX: `atomic run <IMAGE> --mode=genanswers`
  --dry-run             Don't actually call provider. The commands that should
                        be run will be logged but not run.
  --answers-format {ini,json,xml,yaml}
                        The format for the answers.conf.sample file. Default:
                        ini
  --namespace NAMESPACE
                        The namespace to use in the target provider
  --providertlsverify {True,False}
                        Value for providertlsverify answers option.
                        --providertlsverify=False to disable tls verification
  --providerconfig PROVIDERCONFIG
                        Value for providerconfig answers option.
  --providercafile PROVIDERCAFILE
                        Value for providercafile answers option.
  --providerapi PROVIDERAPI
                        Value for providerapi answers option.
  --logtype {cockpit,color,nocolor,none}
                        Override the default logging output. The options are:
                        nocolor: we will only log to stdout; color: log to
                        stdout with color; cockpit: used with cockpit
                        integration; none: atomicapp will disable any logging.
                        If nothing is set and logging to file then 'nocolor'
                        by default. If nothing is set and logging to tty then
                        'color' by default.
```

This LGTM :+1:

**Comment by cdrage** [comment]
Tests pass too :+1:

**Comment by dustymabe** [comment]
So.. here is a problem that is shown in @cdrage's output above:

```
optional arguments:
  -V, --version         show the version and exit.

optional arguments:
  -v, --verbose         Verbose output mode.
```

Basically `optional arguments:` are shown twice, which isn't really ideal. 

One possible way around this is to leave the version option in the globals subparser but simply add this to the toplevel parser:

```
        toplevel_parser.add_argument(
            "-V",
            "--version",
            action='version',
            version='atomicapp %s, Nulecule Specification %s' % (
                __ATOMICAPPVERSION__, __NULECULESPECVERSION__),
            help=argparse.SUPPRESS)
```

so basically we have two --version options (one in toplevel and one in globals) but the one in toplevel would not have any help output because of the `argparse.SUPPRESS`. 

Does that make sense?

**Comment by containscafeine** [comment]
@dustymabe +1
@dustymabe @cdrage How about this? https://github.com/projectatomic/atomicapp/commit/4bce9a27a53623544a9a465ff43ef448dce8c0db

```bash
$ atomicapp --help
usage: atomicapp {run,fetch,stop,genanswers} ...

This will fetch and run an Atomic App, a containerized application conforming to the Nulecule Specification

positional arguments:
  {run,fetch,stop,genanswers}

optional arguments:
  -V, --version         Show the version and exit.
  -v, --verbose         Verbose output mode.
  -q, --quiet           Quiet output mode.
...
...
```

**Comment by cdrage** [comment]
@dustymabe 
Woops. I completely missed that.

```
dropbox/dev/atomicapp  master ✔                                                                                                                                                                                                                        8h32m  
▶ atomicapp --help
usage: atomicapp {run,fetch,stop,genanswers} ...

This will fetch and run an Atomic App, a containerized application conforming to the Nulecule Specification

positional arguments:
  {run,fetch,stop,genanswers}

optional arguments:
  -V, --version         Show the version and exit.
  -v, --verbose         Verbose output mode.
  -q, --quiet           Quiet output mode.
  --mode {fetch,run,stop,genanswers}
                        The mode Atomic App is run in. This option has the
                        effect of switching the 'verb' that was passed by the
                        user as the first positional argument. This is useful
                        in cases where a user is not using the Atomic App cli
                        directly, but through another interface such as the
                        Atomic CLI. EX: `atomic run <IMAGE> --mode=genanswers`
  --dry-run             Don't actually call provider. The commands that should
                        be run will be logged but not run.
  --answers-format {ini,json,xml,yaml}
                        The format for the answers.conf.sample file. Default:
                        ini
  --namespace NAMESPACE
                        The namespace to use in the target provider
  --providertlsverify {True,False}
                        Value for providertlsverify answers option.
                        --providertlsverify=False to disable tls verification
  --providerconfig PROVIDERCONFIG
                        Value for providerconfig answers option.
  --providercafile PROVIDERCAFILE
                        Value for providercafile answers option.
  --providerapi PROVIDERAPI
                        Value for providerapi answers option.
  --logtype {cockpit,color,nocolor,none}
                        Override the default logging output. The options are:
                        nocolor: we will only log to stdout; color: log to
                        stdout with color; cockpit: used with cockpit
                        integration; none: atomicapp will disable any logging.
                        If nothing is set and logging to file then 'nocolor'
                        by default. If nothing is set and logging to tty then
                        'color' by default.

dropbox/dev/atomicapp  master ✔                                                                                                                                                                                                                        8h32m  
▶ atomicapp -V
atomicapp 0.4.3, Nulecule Specification 0.0.2

dropbox/dev/atomicapp  master ✔                                                                                                                                                                                                                        8h32m  
▶ atomicapp -v
usage: atomicapp {run,fetch,stop,genanswers} ...
atomicapp: error: too few arguments
```

this looks better now @containscafeine

**Comment by dustymabe** [comment]
LGTM - if it passes @cdrage then I'm good for merge

**Comment by containscafeine** [comment]
Do I squash the commits?

**Comment by cdrage** [comment]
@containscafeine 
Please do, once you do that i'll run it through tests and merge it.

**Comment by containscafeine** [comment]
@cdrage done, kindly review :)

**Comment by cdrage** [comment]
LGTM

**Pull request merged**
