### PR TITLE
Add namespaced labels to Dockerfile

### LINKED ISSUE #33: Proposal: usage of LABELs in Application's Dockerfile
To give a little more meaning to the dockerfile and make the meta data available to atomic tool (and other tools like devassistant) I would like to propose the following LABELs

`LABEL io.projectatomic.nulecule.specversion 0.0.2` - this indicates, that the Dockerfile belongs to a Atomicapp, compatible with Nulecule Spec 0.0.2, inferred from that, we know that this docker container is an atomicapp.

### PR DESCRIPTION
**Pull request by vpavlin**
Fixes #33

### CODE REVIEW

**Comment by aweiteka** [comment]
We [lost the reference](https://github.com/projectatomic/ContainerApplicationGenericLabels/issues/7) to these namespaced labels. Some more discussion is warranted, I think. I recommend holding off for a bit so we don't go down a path that might change.

**Comment by goern** [comment]
So what I read from the Dockerfile after the merge: This atomicapp will support provider kube, dockah, and openshift. As this is the base image, it has no artifacts at all, and layered images need to overwrite the Label anyways... so putting the list of supported providers in the base image may lead to errors: the layered image may not have overwritten the label, someone asks the layered image about the supported providers and a list that has too many providers will be returned.

**Comment by vpavlin** [comment]
Hmm..I understood this as a list of providers supported by atomicapp (i.e. which providers are implemented).

**Comment by goern** [comment]
So Atomicapp Base Image may support all these, but if the ISV's app does not provide deployment configuration files for it?!

**Comment by vpavlin** [comment]
Yes..I don't know..the difference is in the point of view (and incorrect naming from my side). This definitely should not go in..closing

My point was more to provide a list of implemented providers..but that should be rather an argument in atomicapp cli

**Pull request closed without merging**
