### PR TITLE
initial version of python unittest and coveralls based testing

### PR DESCRIPTION
**Pull request by goern**
I removed shell based tests, as they are replaced by python based tests.

using pytest and coverage, converted to a TestSuite
added an sys.exit() to cli.main.run(), as a CLI should return something.

### CODE REVIEW

**Comment by goern** [comment]
branch passes build at https://travis-ci.org/goern/atomicapp/builds/69707283, resolving the merge conflict manually seems easy. pls merge :)

**Comment by aweiteka** [comment]
@imcleod could you review?

**Comment by aweiteka** [comment]
ping @imcleod

**Comment by vpavlin** [comment]
LGTM

**Pull request merged**
