### PR TITLE
Moved a constant from openshift.py to constants.py

### PR DESCRIPTION
**Pull request by surajssd**
Moved a constant from openshift.py to constants.py for the sake of clarity.

### CODE REVIEW

**Comment by cdrage** [comment]
LGTM :+1:

**Comment by dustymabe** [comment]
I originally left that constant in the file where it was used because that is the only place it is used. If it makes sense to move it to the contstants.py then LGTM.

**Comment by dustymabe** [comment]
#dotests

**Comment by dustymabe** [comment]
#dotests

**Comment by kadel** [comment]
#dotests

**Comment by dustymabe** [comment]
kube test failed due to yum error reaching repos. Trying again.

**Comment by dustymabe** [comment]
#dotestkubernetes

**Comment by dustymabe** [comment]
@cdrage merge away

**Pull request merged**
