### PR TITLE
[Do Not Merge] Adding python-setuptools to requirements.txt

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Fixes issue #371

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by dustymabe** [comment]
marking as Do Not Merge for now until we get the beta3 branch merged.

**Comment by charliedrage** [comment]
Rebase and merge now that beta3 is in? ping @LalatenduMohanty

**Comment by LalatenduMohanty** [comment]
@charliedrage Somehow missed the ping. Will do that

**Comment by dustymabe** [comment]
@LalatenduMohanty since we no longer use setuptools in our docker files then I think we probably don't need to add it as a requirement.

**Comment by LalatenduMohanty** [comment]
@dustymabe Agree. Closing the PR

**Pull request closed without merging**
