### PR TITLE
Changes to verbs for Atomic App 0.3.2 release!

### PR DESCRIPTION
**Pull request by cdrage**
This PR:

- Renames the installation function to fetch
- Changes the naming of deploy/undeploy to run/stop in each provider
- Removes the mention of uninstall code since we are no longer implementing this
- Fix tests as introduced by the new code above

### CODE REVIEW

**Comment by dustymabe** [comment]
need to remove the install label from the Docker images.

**Comment by dustymabe** [comment]
LGTM - @rtnpro and @kadel please review

**Comment by cdrage** [comment]
Tests have just passed against PR 525 with the new commit (remove install labels) as well as a re-base against master again.

**Comment by kadel** [comment]
done couple of test :+1:  LGTM

**Comment by rtnpro** [comment]
Checked out the entire lifecycle of a few atomicapps: ``fetch``, ``run``, ``stop`` and everything looked fine. :+1:  from me.

**Pull request merged**
