### PR TITLE
Support specifying default provider in Nulecule spec file.

### LINKED ISSUE #378: You should be able to provide a default provider within Nulecule
An issue that we're facing is that there is no way to assign a default provider __outside__ of the answers.conf.

If an Atomic App is packaged with only a Docker provider, by running `atomic run cdrage/testimage` the container by default will try to run k8s if no `answers.conf` is provided. 

I propose we add (somewhere) to the Nulecule graph a default provider.

```yaml
metadata:
  name: Hello Apache App
  appversion: 0.0.1
  description: Atomic app for deploying a really basic Apache HTTP server
graph:
  - name: helloapache-app
  - defaultprovider: docker
    params:
      - name: image
        description: The webserver image
        default: centos/httpd
      - name: hostport
        description: The host TCP port as the external endpoint
        default: 80
    artifacts:
      docker:
        - file://artifacts/docker/hello-apache-pod_run
      kubernetes:
        - file://artifacts/kubernetes/hello-apache-pod.json
```

### PR DESCRIPTION
**Pull request by rtnpro**
Fixes #378

### CODE REVIEW

**Comment by dustymabe** [comment]
So I don't really like how we are spreading out the integration of the config in different areas but you added unit tests so when we make changes in the future we should catch any regressions we make. 

I think in the coming time we will do a complete rework of the handling of the config. Until that time this LGTM.

@cdrage. can you run this through your functional tests?

**Comment by rtnpro** [comment]
@dustymabe 

As discussed, in the long run, we need to have a ``Config`` object rather than a dict to handle config data.

**Comment by cdrage** [comment]
Code LGTM. Tests pass too :+1:

**Comment by cdrage** [comment]
Okay, thought it wasn't working, but I was just getting a weird anymarkup yaml error due to random whitespacing being added. 

```
~/test                                                                                                                        
▶ docker build -t test . && sudo atomicapp run test
Sending build context to Docker daemon 38.91 kB
Step 0 : FROM atomicapp:build
 ---> dab9752a306d
Step 1 : MAINTAINER Red Hat, Inc. <container-tools@redhat.com>
 ---> Using cache
 ---> 6a0c6ac97203
Step 2 : LABEL io.projectatomic.nulecule.providers "kubernetes,docker" io.projectatomic.nulecule.specversion "0.0.2"
 ---> Using cache
 ---> 36eb3a8400ff
Step 3 : ADD /Nulecule /Dockerfile README.md /application-entity/
 ---> a13e19a7fa53
Removing intermediate container b4f09cd8581a
Step 4 : ADD /artifacts /application-entity/artifacts
 ---> 7a999e021ff2
Removing intermediate container a47b25c2c4b9
Successfully built 7a999e021ff2
2016-01-19 14:45:40,055 - atomicapp.cli.main - INFO - Action/Mode Selected is: run
2016-01-19 14:45:40,055 - atomicapp.nulecule.base - INFO - Unpacking image: test to /var/lib/atomicapp/test-17e6ca5c77b9
2016-01-19 14:45:42,809 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: test
2016-01-19 14:45:42,809 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: test to /var/lib/atomicapp/test-17e6ca5c77b9
119b519d6458aa37da062578421e86718c7826027aaebd2ef272a52e69123a1f
2016-01-19 14:45:43,159 - atomicapp.cli.main - ERROR - AnyMarkupError: caught <class 'yaml.scanner.ScannerError'>: mapping values are not allowed here
  in "<file>", line 17, column 13
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.1-py2.7.egg/atomicapp/cli/main.py", line 100, in cli_run
    nm.run(**argdict)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.1-py2.7.egg/atomicapp/nulecule/main.py", line 221, in run
    self.nulecule = self.unpack(dryrun=dryrun, config=self.answers)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.1-py2.7.egg/atomicapp/nulecule/main.py", line 126, in unpack
    nodeps=nodeps, dryrun=dryrun, update=update)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.1-py2.7.egg/atomicapp/nulecule/base.py", line 105, in unpack
    dryrun=dryrun, update=update)
  File "/usr/local/lib/python2.7/dist-packages/atomicapp-0.3.1-py2.7.egg/atomicapp/nulecule/base.py", line 130, in load_from_path
    nulecule_data = anymarkup.parse_file(nulecule_path)
  File "build/bdist.linux-x86_64/egg/anymarkup_core/__init__.py", line 114, in parse_file
    return parse(f, format, encoding, force_types)
  File "build/bdist.linux-x86_64/egg/anymarkup_core/__init__.py", line 88, in parse
    raise AnyMarkupError(e)
AnyMarkupError: AnyMarkupError: caught <class 'yaml.scanner.ScannerError'>: mapping values are not allowed here
  in "<file>", line 17, column 13
```

All good now :+1:

**Pull request merged**
