### PR TITLE
Add more legal information

### PR DESCRIPTION
**Pull request by cdrage**
Add missing legal information to the top of each .py file.

### CODE REVIEW

**Comment by cdrage** [comment]
Your wish is granted @goern :)

**Comment by cdrage** [comment]
ping @dustymabe @rtnpro @kadel for review / lgtm

**Comment by dustymabe** [comment]
#dotests

**Comment by dustymabe** [comment]
#dotests

**Comment by dustymabe** [comment]
@cdrage - we have seen the kubernetes issue before. The openshift issue is new. 

https://ci.centos.org/job/atomicapp-test-openshift-pr/39/

**Comment by cdrage** [comment]
@dustymabe 
Could possibly be this: https://bugzilla.redhat.com/show_bug.cgi?id=1293805
https://github.com/openshift/origin/pull/6884

**Comment by dustymabe** [comment]
@cdrage.. looks good for merge. The openshift failing test is something else so I don't see any reason to hold this up.

**Comment by dustymabe** [comment]
rebase and merge plz :)

**Comment by cdrage** [comment]
Mergin'

**Pull request merged**
