### PR TITLE
Add support for embedding answers file in application.

### PR DESCRIPTION
**Pull request by dustymabe**
This has been a use case that has been requested to allow
for someone who is doing deployment of an atomicapp to actually
embed his answers file within the provided atomicapp (via FROM:)
in order to create a new container that has exactly the config
he/she desires.

An example would be that I have decided to package up mariadb with
an answers file that contains all the questions answered already. I
create an answers file with the data in it then create a new container
with a Dockerfile like so:

FROM: projectatomic/mariadb-centos7-atomicapp
ADD /answers.conf /application-entity/

Then the resulting atomicapp can be deployed without anyone having to
create an answers file or answer questions.

### CODE REVIEW

**Comment by kadel** [comment]
LGTM

**Comment by cdrage** [comment]
Okay, from testing it looks like it breaks on `atomic stop`

```
##########
stop: TESTING WORDPRESS EXAMPLE
##########

Sending build context to Docker daemon 47.62 kB
Step 0 : FROM atomicapp:build
 ---> d24013dad7f2
Step 1 : MAINTAINER Red Hat, Inc. <container-tools@redhat.com>
 ---> Running in 3c0f6ee4ebf7
 ---> 742aa30a159a
Removing intermediate container 3c0f6ee4ebf7
Step 2 : LABEL io.projectatomic.nulecule.specversion "0.0.2" io.projectatomic.nulecule.providers "kubernetes,docker,openshift"
 ---> Running in 43d706b9d605
 ---> 8f9278b546eb
Removing intermediate container 43d706b9d605
Step 3 : ADD /Nulecule gpl-3.0.txt /application-entity/
 ---> 9a82ce508985
Removing intermediate container e0b1aefa4a30
Step 4 : ADD /artifacts /application-entity/artifacts
 ---> 5ddc80232934
Removing intermediate container 4cf921dcf3e6
Successfully built 5ddc80232934
Sending build context to Docker daemon 51.71 kB
Step 0 : FROM atomicapp:build
 ---> d24013dad7f2
Step 1 : MAINTAINER Christoph Görn <goern@redhat.com>
 ---> Running in 3527ecc8fd7f
 ---> ebfa0da00bcf
Removing intermediate container 3527ecc8fd7f
Step 2 : LABEL io.projectatomic.nulecule.specversion "0.0.2" io.projectatomic.nulecule.providers "kubernetes, openshift, docker" Build "docker build --rm --tag test/wordpress-centos7-atomicapp ."
 ---> Running in d47d810fbcd9
 ---> 23fb0c00aaa2
Removing intermediate container d47d810fbcd9
Step 3 : ADD /Nulecule /Dockerfile README.md gpl-3.0.txt /application-entity/
 ---> 0f5f44aca0a2
Removing intermediate container 1fe3b5f2bcd0
Step 4 : ADD /artifacts /application-entity/artifacts
 ---> 22cb434a06c0
Removing intermediate container 799ef3a01b35
Successfully built 22cb434a06c0
docker run -it --rm  --privileged -v /home/wikus/dropbox/dev/adb-tests/cdrage-atomicapp-ci:/atomicapp -v /run:/run -v /:/host --net=host --name wordpress -e NAME=wordpress -e IMAGE=wordpress wordpress -v  stop  --provider=docker build/
2016-01-14 16:52:54,481 - __main__ - INFO - Action/Mode Selected is: stop
2016-01-14 16:52:54,481 - __main__ - DEBUG - Final parsed cmdline: stop -v --provider=docker build/
2016-01-14 16:52:54,481 - atomicapp.nulecule.main - DEBUG - NuleculeManager init app_path: build/
2016-01-14 16:52:54,481 - atomicapp.nulecule.main - DEBUG - NuleculeManager init    image: None
2016-01-14 16:52:54,490 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2016-01-14 16:52:54,491 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2016-01-14 16:52:54,492 - atomicapp.nulecule.base - INFO - Found existing external application for aggregated-mariadb-atomicapp. Loading it.
2016-01-14 16:52:54,498 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2016-01-14 16:52:54,499 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
2016-01-14 16:52:54,500 - atomicapp.plugin - DEBUG - Loading providers from /opt/atomicapp/atomicapp/providers
db_user (Database User): ^Cmariadb-atomicapp-app
```

Not being able to detect what's in the generated answers.conf.gen file:
```
adb-tests/cdrage-atomicapp-ci/build  master ✗                                                                                                                                                                                                        1h20m ◒  
▶ cat answers.conf.gen 
[wordpress]
image = wordpress
db_pass = foo
db_name = foo
db_user = foo
db_host = mariadb:3306
port = 8080
[mariadb-atomicapp]
db_pass = foo
db_name = foo
db_user = foo
root_pass = MySQLPass
[general]
namespace = foobar
provider = docker% 
```

**Comment by dustymabe** [comment]
Found the bug: self.answer_file != self.answers_file :)

**Comment by cdrage** [comment]
Okay, from testing and code-review, everything LGTM'. :+1:

**Pull request merged**
