### PR TITLE
Change tmp dir location

### PR DESCRIPTION
**Pull request by cdrage**
Renamed branch for https://github.com/projectatomic/atomicapp/pull/402 pull

### CODE REVIEW

**Comment by vpavlin** [comment]
lgtm

**Comment by dustymabe** [comment]
Can you add the wording in the first comment in #402 into the commit message? I think it is useful.

**Comment by cdrage** [comment]
@dustymabe sorry, i'm a bit confused from both comments, what wording into the commit? I believe I did by changing the commit message to "Change tmp dir location"

**Comment by dustymabe** [comment]
@cdrage I'm talking about the first comment on #402 . The one that starts with "Imo, we should be extracting to". I think that information would be useful in the commit message. So just git `commit --amend` the commit and edit the commit message if you agree.

**Comment by rtnpro** [comment]
:+1: LGTM

**Comment by cdrage** [comment]
@dustymabe updated

**Comment by dustymabe** [comment]
looks good

**Pull request merged**
