### PR TITLE
cli: allow specifying target dir during atomic run

### PR DESCRIPTION
**Pull request by dustymabe**
This commit has one simple goal which is to allow `atomic run` to
be executed against an installed directory just a little easier.

Before this commit we need:

    atomic install myapp --destination=/path/to/local/dir
    atomic run myapp --destination=/path/to/local/dir

After this commit:

    atomic install myapp --destination=/path/to/local/dir
    atomic run myapp /path/to/local/dir

### CODE REVIEW

**Comment by rtnpro** [comment]
More intuitive. LGTM :+1:

**Comment by kadel** [comment]
why don't we allow same thing for install? eg. `atomic install myapp /path/to/local/dir`

**Comment by dustymabe** [comment]
'/path/to/local/dir' is a path to an "existing" application that has been extracted. In the case of `install` there is not yet an "existing" application, otherwise you wouldn't be calling `install`.

Does that make sense?

**Comment by cdrage** [comment]
LGTM :+1: and all tests pass!

**Pull request merged**
