### PR TITLE
Throw error during running application on  provider missing from artifacts

### LINKED ISSUE #337: Not failing if provider config isn't provided.
Used projectatomic/helloapache and removed the Docker provider from `Nulecule` as well as the artifact.

Weirdly, this doesn't cause cdk2-beta3-rc1 to fail.

```
▶ atomicapp -v run --provider=docker hello
2015-10-16 12:28:14,011 - atomicapp.plugin - DEBUG - Loading providers from /usr/local/lib/python2.7/dist-packages/atomicapp-0.1.11-py2.7.egg/atomicapp/providers
2015-10-16 12:28:14,018 - atomicapp.nulecule.base - INFO - Unpacking image: hello to /home/wikus/test2
2015-10-16 12:28:14,330 - atomicapp.nulecule.container - INFO - Skipping pulling Docker image: hello
2015-10-16 12:28:14,330 - atomicapp.nulecule.container - INFO - Extracting nulecule data from image: hello to /home/wikus/test2
2015-10-16 12:28:14,330 - atomicapp.nulecule.container - DEBUG - Running Docker container: /usr/bin/docker run -d --entrypoint /bin/true hello
2015-10-16 12:28:14,635 - atomicapp.nulecule.container - DEBUG - Copying data from Docker container: /usr/bin/docker cp 497034c884990deb6d501ebbcc7b4b3dbe26624a2f65dd22a8bd05e3ce226fdd:/application-entity /tmp/nulecule-e64f83a0-7422-11e5-8f59-3402868080db
2015-10-16 12:28:14,706 - atomicapp.nulecule.container - DEBUG - Copying nulecule data from /tmp/nulecule-e64f83a0-7422-11e5-8f59-3402868080db/application-entity to /home/wikus/test2
2015-10-16 12:28:14,707 - atomicapp.nulecule.container - DEBUG - Removing tmp dir: /tmp/nulecule-e64f83a0-7422-11e5-8f59-3402868080db
2015-10-16 12:28:14,708 - atomicapp.nulecule.container - DEBUG - Removing Docker container: /usr/bin/docker rm -f 497034c884990deb6d501ebbcc7b4b3dbe26624a2f65dd22a8bd05e3ce226fdd
497034c884990deb6d501ebbcc7b4b3dbe26624a2f65dd22a8bd05e3ce226fdd
2015-10-16 12:28:14,834 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2015-10-16 12:28:14,834 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-16 12:28:14,834 - atomicapp.plugin - DEBUG - Found provider <class 'docker.DockerProvider'>
2015-10-16 12:28:14,834 - atomicapp.plugin - WARNING - Configuration option 'providerconfig' not found
2015-10-16 12:28:14,834 - docker - DEBUG - Given config: {u'image': u'centos/httpd', u'hostport': 80, 'namespace': 'default', 'provider': 'kubernetes'}
2015-10-16 12:28:14,835 - docker - DEBUG - Namespace: default
2015-10-16 12:28:14,848 - docker - INFO - Deploying to provider: Docker
```

```
~/test2                                                                                                                                                                                                                                                       
▶ d ps -a                                 
CONTAINER ID        IMAGE                  COMMAND                CREATED             STATUS              PORTS               NAMES
f1dac9a96c03        rh_email               "mutt-patched -F ~/.   About an hour ago   Up About an hour                        rh_email            
1c3dfdfb5ebd        rh_vpn                 "openvpn --config /e   2 hours ago         Up 2 hours                              rh_vpn              
35cf3b9ca74f        charliedrage/dropbox   "/bin/sh -c /startup   6 weeks ago         Up 2 hours                              dropbox  
```

And nothing deployed ^^ 

As you can see, it *warns* you saying that providerconfig is not found, however, it does *not* fail. In comparison to atomicapp 1.11.

We *may* have to change how

```python
    def checkConfigFile(self):                                                                                                                                                                                                                                 
        if not self.config_file or not os.access(self.config_file, os.R_OK):                                                                                                                                                                                   
            try:                                                                                                                                                                                                                                               
                self.generateConfigFile()                                                                                                                                                                                                                      
            except NotImplementedError:                                                                                                                                                                                                                        
                raise ProviderFailedException(                                                                                                                                                                                                                 
                    "Cannot access configuration file %s. Try adding "                                                                                                                                                                                         
                    "'%s = /path/to/your/%s' in the "                                                                                                                                                                                                          
                    "[general] section of the answers.conf file."                                                                                                                                                                                              
                    % (self.config_file, PROVIDER_CONFIG_KEY, DEFAULT_PROVIDER_CONFIG))  
```

works

### PR DESCRIPTION
**Pull request by rtnpro**
Fixes #337

### CODE REVIEW

**Comment by charliedrage** [comment]
So now there's two implementations of erroring out when no providerconfig is provided?
Please see: https://github.com/projectatomic/atomicapp/pull/348/files

Correct me if I'm wrong!

**Comment by rtnpro** [comment]
@charliedrage 
While https://github.com/projectatomic/atomicapp/pull/348/files takes care of checking provider config, this fix takes care of the case where you're trying to run an application with a provider which had no corresponding artifact files in the nulecule component.

**Comment by vpavlin** [comment]
LGTM

**Comment by dustymabe** [comment]
LGTM - I'll let charlie take a look since you asked him a question.

**Comment by charliedrage** [comment]
Question answered. Thanks :) LGTM :+1:

**Pull request merged**
