### PR TITLE
Remove ASCII art

### PR DESCRIPTION
**Pull request by cdrage**
Remove ASCII art in favour of a more minimalistic logging

### CODE REVIEW

**Comment by dustymabe** [comment]
So it might be good to include in the commit message why we decided to remove it. 

Also could we merge the "replacement" text down to just a single line of output? I think the ultimate goal is to reduce the number of lines - if we still had the same number of lines I'd rather just keep the ascii art.

@jberkus - want to comment?

**Comment by cdrage** [comment]
@dustymabe @jberkus 
What type of formatting would you like for the versioning / nulecule versioning, name of the application, etc? Could you give me an example?

**Comment by dustymabe** [comment]
@cdrage - a single line like this maybe:

```
INFO   :: - cli/main.py :: Atomic App: 0.5.2 - Nulecule: 0.0.2 - Mode: Run
```

Same Amount of Information - single line

That brings up a nother question - what exactly is the Nulecule version we are printing out? Is it the minimum supported by Atomic App? Is it the maximum?

**Comment by cdrage** [comment]
@dustymabe Updated with your suggestions.

Hmmm. Recommended Nulecule version?

**Comment by dustymabe** [comment]
> Hmmm. Recommended Nulecule version?

Yeah I don't really know what it is - we keep it as a constant in the code. Do we use it anywhere?

**Comment by cdrage** [comment]
@dustymabe 
Other than `atomicapp init`, nope.

**Comment by dustymabe** [comment]
@cdrage - hmm so I think what is is supposed to indicate is what version/versions we are supposed to support.

it should probably show the "minimum" supported version - or we could just not output that information for now since we can't even really determine why it's useful

**Comment by cdrage** [comment]
@dustymabe we can just output Atomic App version and the run mode. No need for Nulecule spec version

**Comment by dustymabe** [comment]
> @dustymabe we can just output Atomic App version and the run mode. No need for Nulecule spec version

+1

**Comment by cdrage** [comment]
@dustymabe updated, feel free to have a look over and LGTM it :)

**Comment by dustymabe** [comment]
+1

**Comment by cdrage** [comment]
#dotests

**Pull request merged**
