### PR TITLE
refactor exceptions, fix #621, fix #622

### LINKED ISSUE #621: `atomicapp fetch` errors with traceback if docker daemon is not running
```bash
$ sudo atomicapp fetch --destination localdir projectatomic/helloapache  -v                                                
2016-03-11 18:31:42,293 - [INFO] - cli/main.py - Action/Mode Selected is: fetch
2016-03-11 18:31:42,293 - [DEBUG] - cli/main.py - Final parsed cmdline: fetch --destination localdir projectatomic/helloapache -v
2016-03-11 18:31:42,294 - [DEBUG] - nulecule/main.py - NuleculeManager init app_path: localdir
2016-03-11 18:31:42,294 - [DEBUG] - nulecule/main.py - NuleculeManager init image: projectatomic/helloapache
2016-03-11 18:31:42,294 - [DEBUG] - nulecule/main.py - Request to unpack to projectatomic/helloapache to localdir
2016-03-11 18:31:42,294 - [INFO] - nulecule/base.py - Unpacking image: projectatomic/helloapache to localdir
2016-03-11 18:31:42,343 - [ERROR] - cli/main.py - Could not connect to the docker daemon.
Traceback (most recent call last):
  File "/home/vagrant/atomicapp/atomicapp/cli/main.py", line 77, in cli_fetch
    nm.fetch(**argdict)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 186, in fetch
    self.nulecule = self.unpack(update, dryrun, config=self.answers)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/main.py", line 129, in unpack
    nodeps=nodeps, dryrun=dryrun, update=update)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/base.py", line 103, in unpack
    docker_handler = DockerHandler(dryrun=dryrun)
  File "/home/vagrant/atomicapp/atomicapp/nulecule/container.py", line 42, in __init__
    raise DockerException("Could not connect to the "
DockerException: Could not connect to the docker daemon.
```

### LINKED ISSUE #622: same exceptions being caught for cli*() in cli/main.py
We are currently catching the following same exceptions:

```python
    except DockerException as e:
        logger.error(e)
        sys.exit(1)
    except NuleculeException as e:
        logger.error(e)
        sys.exit(1)
    except Exception as e:
        logger.error(e, exc_info=True)
        sys.exit(1)
```
in `cli_genanswers`, `cli_fetch`, `cli_run`, `cli_stop`.

This leads to:
- code being replicated
- a possibility of not catching exceptions in other functions if caught in one, which has led to issue #621, https://github.com/projectatomic/atomicapp/issues/621#issuecomment-195778842

### PR DESCRIPTION
**Pull request by containscafeine**
About https://github.com/projectatomic/atomicapp/commit/3aa144ae4110341ec9afe887c4e074e295f5573d

I have removed the `try-except` block from `cli_genanswers`, `cli_fetch`, `cli_run`, `cli_stop` since `except` clause was/should be the same for all of those, and moved the `except` statements to another function [`cli_func_exec`](https://github.com/containscafeine/atomicapp/commit/3aa144ae4110341ec9afe887c4e074e295f5573d#diff-91e24f7bd4ae0b7cae29db3faca25ff6R116).

So now, during cli.run(), instead of `args.func(args)`, [`cli_func_exec(args.func, args)`](https://github.com/containscafeine/atomicapp/commit/3aa144ae4110341ec9afe887c4e074e295f5573d#diff-91e24f7bd4ae0b7cae29db3faca25ff6R443) is called which further executes the specified `cli_*` function, but catches all the exceptions itself instead of each `cli_*` function having to worry about those.

@dustymabe @cdrage does this make sense?

### CODE REVIEW

**Comment by dustymabe** [comment]
#dotests

**Comment by dustymabe** [comment]
#dotests

**Comment by dustymabe** [comment]
#dotests

**Comment by dustymabe** [comment]
#dotests

**Comment by cdrage** [comment]
@containscafeine 

Nice work! :D don't see anything wrong with the code.

Tests centos-ci pass and my local tests pass too.

LGTM :+1:

**Comment by cdrage** [comment]
I don't see any issue with this code and the tests have passed (three times now :)).

Merging!

**Pull request merged**
