### PR TITLE
Added Makefile

### PR DESCRIPTION
**Pull request by charliedrage**
Added Makefile, creates some sweet aliases. Satisfies the developer OCD.

Makes everything a little bit easier for local dev / install and for future installations / testing. More aliases can be added here. HINT HINT: `make dev` to Vagrant possibly? :)

```
COMMAND
ALIAS
```

```
make 
(default) python -m pytest -vv
```

````
make install
python setup.py install .
```

```
make test
python -m pytest -vv
```

```
make tag=atomicapp image
docker build -t atomicapp image
```

```
make syntax-check
flake8 atomicapp
```

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@charliedrage I like the idea :) . LGTM

**Comment by charliedrage** [comment]
@vpavlin @goern @dustymabe 

need one more opinion before merge :) want to get this in so we can add it more easily to a testing unit test bash script

**Comment by vpavlin** [comment]
hmm..I would probably expect the default for `make`  to be a `make image` with some predefined `$tag`..but that's just me:)

Otherwise LGTM

**Comment by goern** [comment]
hehe... needs_doc :)

**Pull request merged**
