### PR TITLE
provider testing fix

### PR DESCRIPTION
**Pull request by charliedrage**
Redo unit tests for new refactor :)

### CODE REVIEW

**Comment by dustymabe** [comment]
`test_kubernetes_provider.py ` could use some short descriptions for the functions like `test_docker_provider.py` does. Do you think you can add that?

Other than that LGTM - Let's get a +1 from @rtnpro and then push.

**Comment by charliedrage** [comment]
@rtnpro @dustymabe 

Note: Everything provider wise works except for
`tests/units/providers/test_kubernetes_provider.py::TestKubernetesProviderBase::test_provider_check_config_fail`

This is blocked by issue #337

**Comment by charliedrage** [comment]
Updated comments too ^^

**Comment by dustymabe** [comment]
LGTM

**Comment by goern** [comment]
@vpavlin I cant eval if code is ok

**Comment by vpavlin** [comment]
LGTM

**Pull request merged**
