### PR TITLE
move openshift._make_request() to Utils.make_rest_request()

### PR DESCRIPTION
**Pull request by kadel**
Other providers can make use of this function now.

### CODE REVIEW

**Comment by kadel** [comment]
Hmm :-( Now I not sure if this is great idea.
I cannot rise `ProviderFailedException` here :-(

Whole point of this function was so I don't have to catch exceptions each time i want to make request.

**Comment by kadel** [comment]
I had to change raising `ProviderFailedException` to `AtomicAppUtilsException`.

**Comment by cdrage** [comment]
LGTM

**Comment by dustymabe** [comment]
LGTM

**Pull request merged**
