### PR TITLE
Switch from subprocess to Utils.run_cmd(cmd)

### PR DESCRIPTION
**Pull request by cdrage**
Similar to the Kubernetes provider, use run_cmd for more stdout and
stderr approach for debugging.

First part of a fix for:

https://github.com/projectatomic/atomicapp/issues/590

Second part will be a different output (show the error code!) :)

### CODE REVIEW

**Comment by cdrage** [comment]
Tests pass :+1:

**Comment by dustymabe** [comment]
Hey @cdrage - so what would be the 2nd part to #590? 

Right now here is the diff between master and this PR:

Master:
```
2016-03-07 22:36:52,390 - [INFO] - main.py - Action/Mode Selected is: run
2016-03-07 22:36:52,404 - [WARNING] - plugin.py - Configuration option 'providerconfig' not found
2016-03-07 22:36:52,405 - [WARNING] - plugin.py - Configuration option 'providerconfig' not found
2016-03-07 22:36:52,522 - [INFO] - docker.py - Deploying to provider: Docker
flag provided but not defined: -x
See 'docker run --help'.
2016-03-07 22:36:52,574 - [ERROR] - main.py - Command '['docker', 'run', u'--name=default_centos-httpd_a4ee5dad604d', '-x', '-d', '-p', '80:80', 'centos/httpd']' returned non-zero exit status 2
Traceback (most recent call last):
  File "/opt/atomicapp/atomicapp/cli/main.py", line 101, in cli_run
    nm.run(**argdict)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 233, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 165, in run
    component.run(provider_key, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 298, in run
    provider.run()
  File "/opt/atomicapp/atomicapp/providers/docker.py", line 106, in run
    subprocess.check_call(cmd)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'run', u'--name=default_centos-httpd_a4ee5dad604d', '-x', '-d', '-p', '80:80', 'centos/httpd']' returned non-zero exit status 2
```

This PR:
```
2016-03-07 22:34:13,907 - [INFO] - main.py - Action/Mode Selected is: run
2016-03-07 22:34:13,923 - [WARNING] - plugin.py - Configuration option 'providerconfig' not found
2016-03-07 22:34:13,923 - [WARNING] - plugin.py - Configuration option 'providerconfig' not found
2016-03-07 22:34:14,035 - [INFO] - docker.py - Deploying to provider: Docker
2016-03-07 22:34:14,100 - [ERROR] - main.py - cmd: ['docker', 'run', u'--name=default_centos-httpd_79080ae13b6e', '-x', '-d', '-p', '80:80', 'centos/httpd'] failed: 
flag provided but not defined: -x
See 'docker run --help'.
Traceback (most recent call last):
  File "/opt/atomicapp/atomicapp/cli/main.py", line 101, in cli_run
    nm.run(**argdict)
  File "/opt/atomicapp/atomicapp/nulecule/main.py", line 233, in run
    self.nulecule.run(cli_provider, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 165, in run
    component.run(provider_key, dryrun)
  File "/opt/atomicapp/atomicapp/nulecule/base.py", line 298, in run
    provider.run()
  File "/opt/atomicapp/atomicapp/providers/docker.py", line 106, in run
    Utils.run_cmd(cmd)
  File "/opt/atomicapp/atomicapp/utils.py", line 266, in run_cmd
    "cmd: %s failed: \n%s" % (str(cmd), stderr))
AtomicAppUtilsException: cmd: ['docker', 'run', u'--name=default_centos-httpd_79080ae13b6e', '-x', '-d', '-p', '80:80', 'centos/httpd'] failed: 
flag provided but not defined: -x
See 'docker run --help'.
```

**Comment by cdrage** [comment]
@dustymabe Yes sir. It's the second part.

Although it's still "dirty" it shouldn't give a stack-trace, rather than an error code (tell user to see the docker logs, etc.) similar to what @jberkus has said.

**Comment by dustymabe** [comment]
So just to be clear.. This PR is the 1st part of #590, right. And there is a 2nd PR coming for the 2nd part of #590. 

@jberkus said specifically we should have an error message that looks something like:
```
container __name__ failed to start with error code __number__
```

Should we add the 2nd part of #590 to this PR?

**Comment by cdrage** [comment]
@dustymabe 
I see what you mean, sorry about that. It'd be better if I just added this commit in here!

I'll update this PR.

**Comment by jberkus** [comment]
Yeah, the language I gave was just a suggestion.  What we're trying to avoid is the stack trace.

On 2016 3 8 16:27:37 GMT+00:00, Charlie Drage <notifications@github.com> wrote:
>@dustymabe Yes sir. It's the second part.
>
>Although it's still "dirty" it shouldn't give a stack-trace, rather
>than an error code (tell user to see the docker logs, etc.) similar to
>what @jberkus has said.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/projectatomic/atomicapp/pull/594#issuecomment-193849927

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dustymabe** [comment]
#dotests

**Comment by cdrage** [comment]
Should we go forward with merging this @dustymabe ?

We would have to parse the actual error output from each provider in order to get the statuses right?  As what @jberkus said we parse each error code (1,0,etc.) from the container in order to get the proper format.

For example, if it fails in docker we would automatically do a `docker logs foobar` of the container when it's launched. Same goes with kubectl. Thoughts?

**Comment by cdrage** [comment]
I'm going to re-open this as a separate PR when I evaluating the Docker provider and implement @jberkus suggestion on error codes.

**Pull request closed without merging**
