### PR TITLE
add  PROVIDERS constant

### PR DESCRIPTION
**Pull request by kadel**
Replace two same lists in argument parsing with constant

### CODE REVIEW

**Comment by charliedrage** [comment]
Would `PROVIDERS` be a better name?

--------------------------------------------
Charlie Drage
4096R / 0x9B3B446C
http://pgp.mit.edu/pks/lookup?op=get&search=0x622CDF119B3B446C
--------------------------------------------

**Comment by kadel** [comment]
It would ;-)

**Comment by charliedrage** [comment]
LGTM :+1:

**Comment by rtnpro** [comment]
:+1: from me

**Pull request merged**
