### PR TITLE
Clean up parsing

### PR DESCRIPTION
**Pull request by cdrage**
Cleans up parsing as to not include the --provider information in
unneeded commands such as init.

Ex.
```
▶ atomicapp init asdfsadf --help
usage: atomicapp init [-h] [-V] [-v] [-q]
                      [--logtype {cockpit,color,nocolor,none}]
                      [--destination DESTINATION]
                      app_name

positional arguments:
  app_name              App name.

optional arguments:
  -h, --help            show this help message and exit
  -V, --version         Show the version and exit.
  -v, --verbose         Verbose output mode.
  -q, --quiet           Quiet output mode.
  --logtype {cockpit,color,nocolor,none}
                        Override the default logging output. The options are:
                        nocolor: we will only log to stdout; color: log to
                        stdout with color; cockpit: used with cockpit
                        integration; none: atomicapp will disable any logging.
                        If nothing is set and logging to file then 'nocolor'
                        by default. If nothing is set and logging to tty then
                        'color' by default.
  --destination DESTINATION
                        Path to the directory where the Atomic App is to be
                        initialized.
```

### CODE REVIEW

**Comment by cdrage** [comment]
ping @dustymabe @rtnpro

**Comment by cdrage** [comment]
@rtnpro or @kadel can you please review this?

**Comment by cdrage** [comment]
#maketests

**Comment by cdrage** [comment]
#dotests

**Comment by kadel** [comment]
LGTM

**Comment by cdrage** [comment]
Going to run tests again just-in-case

**Comment by cdrage** [comment]
#dotests

**Comment by cdrage** [comment]
Not exactly high priority, but once @dustymabe gives his A-OK we can merge in :)

**Pull request merged**
