### PR TITLE
Implement stop for OpenShift provider

### LINKED ISSUE #135: implement STOP for OpenShift provider
see https://trello.com/c/k14cmfdj

### PR DESCRIPTION
**Pull request by aweiteka**
There are several ways to stop resources on
OpenShift. The simplest and most analagous to
stop is "stop". This will stop and delete but
it is not surprising since that's what the oc
command does.

resolves #135 

Note: we do not support stop from template yet since this is a bit more complex.

### CODE REVIEW

**Comment by goern** [comment]
LGTM

**Comment by vpavlin** [comment]
I checked the `oc stop` command and found https://github.com/openshift/origin/blob/master/docs/generated/oc_by_example_content.adoc#oc-stop

which says _Deprecated_, so I asked OpenShift guys and they told me we should use `oc delete` instead.

**Comment by aweiteka** [comment]
@vpavlin good to know! Ok, so let's not merge this as is. Options:

1. Change `atomic stop` to call `oc delete`. This doesn't feel right; it feels too destructive for a stop action.
1. There is no other option. :)

**Comment by goern** [comment]
If we assume that 'stopping an Atomic App' means, that we want to leave it deployed but not any part of it is running, than we should
1. figure out if a replication controller is deployed
1.1. if so, set the number of replicas to 0
2. figure out if any pods are deployed
2.1. if so, delete the pods

This will leave all the DC, BC and RC and templates in place (aka deployed) and stop all execution of the application (aka the pods)

Starting the Atomic App again will result in redeploying any pod configuration and/or setting the number of replicas to 1.

**Comment by aweiteka** [comment]
@goern so there *is* another option. I agree. I'll rework this to handle it less destructively. This begs the question: how do we remove the app? `uninstall` seems like a good fit but does not match the current `install` behavior. That topic is another discussion and PR, I think.

**Comment by aweiteka** [comment]
Need to update using same approach as #221 by @navidshaikh

**Comment by aweiteka** [comment]
Based on current OpenShift provider direction (see #321) I don't think this is required any more. The plan to rely on native OpenShift control (`oc` client or web UI) to control lifecycle outside of run.

**Comment by cdrage** [comment]
Hey @aweiteka can we close this as we're close to implement the API only implementation for openshift?

**Comment by dustymabe** [comment]
@kadel is working on the stop for openshift provider using the new openshift API code.

I'll close this once we have a new PR or Issue # to reference.

**Comment by kadel** [comment]
I've just crated issue for stop for new OpenShift provider  #458

**Comment by dustymabe** [comment]
Closed in favor of issue #458 and future work to resolve it.

**Pull request closed without merging**
