### PR TITLE
[WIP] Add Alpine Linux Dockerfile

### LINKED ISSUE #544: Consider rebasing Atomic App image on a stripped-down OS
The atomicapp example container, based on CentOS7, is 289MB in size.  That's very large for an empty container.   If we want people to actually build their apps on top of it, then it needs to be smaller ... in the neighborhood of 30 to 50MB.  

Would it be possible for us to obtain or produce a stripped-down OS for a smaller image?

### PR DESCRIPTION
**Pull request by cdrage**
Yay < 80Mb Docker image! :sparkles:

Uses the Docker binary at the momen.

In the future, the Docker provider will be replaced by API commands to the Docker daemon rather than cmd line running, making this image even smaller, reducing it to 60Mb. 

Fixes #544

Referencing #390 due to previous discussion as we initially said no. Since we have a lot more images now, may be nice to include this as "experimental"?

From initial tests seems that this builds correctly / works well.

### CODE REVIEW

**Comment by cdrage** [comment]
Perhaps we can make this the default in the future due to our increasing size (300MB+ :-1: )

**Comment by cdrage** [comment]
Hey @jberkus was just wondering if you happened to test this as well? It works my end from the limited testing I've done. We can add this is as an experimental feature until it's 100% robust.

**Comment by jberkus** [comment]
@cdrage no, I haven't had time to build anything since DevConf.  I'll be doing some this week, though.

However ... strategy for Atomic Host seems to be that we want systemd inside the containers, which means looking at a stripped-down version of Fedora instead of Alpine, in the long run.  There's some real advantages to this provided that the issues can be worked out.

So I'm not sure that making Alpine default for Atomic.app is the way to go, given that.

**Comment by dustymabe** [comment]
@cdrage - I am getting an error when trying to build and run with this (see below) - perhaps rebase and make sure it still works for you.
```
2016-03-01 22:17:02,666 - kubernetes - INFO - Deploying to Kubernetes
2016-03-01 22:17:02,666 - kubernetes - DEBUG - ./artifacts/kubernetes/.mariadb-pod.yaml
2016-03-01 22:17:02,673 - kubernetes - DEBUG - ./artifacts/kubernetes/.mariadb-service.yaml
2016-03-01 22:17:02,681 - __main__ - ERROR - [Errno 2] No such file or directory
```

**Comment by cdrage** [comment]
@dustymabe 
hmmm so it looks like it works normally via actual `atomicapp`. but not via `atomic`

**Comment by cdrage** [comment]
woops wrong button, reopened

**Comment by dustymabe** [comment]
@cdrage I run atomicapp via the alias.. so similar to what atomic cli does, but not the same. I guess you need to test using that case. No rush, just probably need to make sure that works

**Comment by cdrage** [comment]
Ahhhhh, I'm encountering an issue with the Docker binary within Alpine. I'm going to test this a bit more.

**Comment by cdrage** [comment]
I'm going to close this for now as I'm working on getting a Python binary file working (it's 8mb total) and use FROM SCRATCH instead.

**Pull request closed without merging**
