### PR TITLE
0.6.3 Release

### PR DESCRIPTION
**Pull request by cdrage**

### CODE REVIEW

**Comment by cdrage** [comment]
ping @rtnpro @dustymabe @kadel for a lgtm

**Comment by cdrage** [comment]
Going to try this locally tomorrow, Seems to be timing out on CentOS CI

**Comment by cdrage** [comment]
#dotests

**Comment by cdrage** [comment]
unittest within centos ci is a false positive, (hopefully) fixed in https://github.com/projectatomic/atomicapp/pull/797 , otherwise, all good from here :+1:

**Comment by dustymabe** [comment]
LGTM

**Pull request merged**
