### PR TITLE
Update docs / more clarity on cli comparison

### PR DESCRIPTION
**Pull request by cdrage**
Create more spacing / update markdown clarity on CLI comparisons

### CODE REVIEW

**Comment by kadel** [comment]
What if we put that comparison to table?
It might get even clearer.

something like this:

|            | atomicapp | atomic |
|----------|-----------|--------|
| fetch    |  `atomicapp fetch ...` | `atomic run ...` |
| run      |
| stop     | 
|genanswers|

**Comment by cdrage** [comment]
@kadel woah, much better, I'm an idiot >.>

I'll update the PR with that change.

**Comment by cdrage** [comment]
@kadel updated based on your comments, thanks! :)

**Comment by kadel** [comment]
:+1:  LGTM :wink:

**Pull request merged**
